otus_homework5: VectorEditorController Class Reference
VectorEditorController Class Reference
Represents a controller for a vector editor.
#include <VectorEditorController.h>
Public Member Functions
VectorEditorController ()
void openDocument (std::string_view filePath)
Opens a document in the vector editor.
void closeDocument ()
Closes the active document in the vector editor.
void saveDocument (std::string_view filePath)
Saves the active document to a file.
void createDocument ()
Create a new document in the vector editor.
void addLine ()
Adds a Line primitive to the active document.
void addRectangle ()
This function is used to add a rectangle to the model.
void deleteSelectedGraphicsPrimitive ()
Deletes the selected graphics primitive from the vector editor model.
void selectGraphicsPrimitives (Point point)
Selects graphics primitives based on the given point.
void undo ()
Undo the last action performed.
void redo ()
Redo the last undone action.
Detailed Description
Represents a controller for a vector editor.
The VectorEditorController class is responsible for handling user interaction with the vector editor. It provides functions to open, close, save, and create documents, as well as add and delete graphics primitives. It also allows users to select, undo, and redo actions performed in the editor.
Definition at line 34 of file VectorEditorController.h.
Constructor & Destructor Documentation
VectorEditorController()
VectorEditorController::VectorEditorController ()
Definition at line 3 of file VectorEditorController.cpp.
{
     _model = std::make_shared<VectorEditorModel>();
     _view = std::make_shared<VectorEditorView>();
     _view->setModel(_model);
 }
Member Function Documentation
addLine()
void VectorEditorController::addLine ()
Adds a Line primitive to the active document.
This function creates a CreatePrimitiveAction with the model as a parameter. The action is then executed to create a Line primitive and add it to the active document. Finally, the action is added to the action history stack.
See also
CreatePrimitiveAction
Definition at line 49 of file VectorEditorController.cpp.
{
     std::cout << "command Add line" << std::endl;
     auto action = std::make_shared<CreatePrimitiveAction<Line>>(_model);
     action->Execute();
     _actionHistory.push( action );
 }
Referenced by main().
addRectangle()
void VectorEditorController::addRectangle ()
This function is used to add a rectangle to the model.
The function creates a new rectangle using the CreatePrimitiveAction class and executes it. It then adds the action to the action history.
Warning
The function assumes that the _model and _actionHistory variables have been properly initialized.
Returns
None.
Definition at line 56 of file VectorEditorController.cpp.
{
     std::cout << "command Add rectangle" << std::endl;
     auto action = std::make_shared<CreatePrimitiveAction<Rectangle>>(_model);
     action->Execute();
     _actionHistory.push( action );
 }
Referenced by main().
closeDocument()
void VectorEditorController::closeDocument ()
Closes the active document in the vector editor.
This function closes the active document in the vector editor. If there are unsaved changes in the document, it will prompt the user to save before closing.
The function creates a CloseDocumentAction to execute the close document operation, which sets the active document to nullptr.
The function then adds the action to the action history stack.
Definition at line 27 of file VectorEditorController.cpp.
{
     //TODO check last save and save if it is need
     std::cout << "command Close document" << std::endl;
     auto action = std::make_shared<CloseDocumentAction>(_model);
     action->Execute();
     _actionHistory.push( action );
 }
Referenced by main().
createDocument()
void VectorEditorController::createDocument ()
Create a new document in the vector editor.
This function creates a new document in the vector editor by executing a CreateDocumentAction. The action sets the active document with a new instance of VectorDocument. After executing the action, it is added to the action history stack.
See also
CreateDocumentAction
Definition at line 42 of file VectorEditorController.cpp.
{
     std::cout << "command Create document" << std::endl;
     auto action = std::make_shared<CreateDocumentAction>(_model);
     action->Execute();
     _actionHistory.push( action );
 }
deleteSelectedGraphicsPrimitive()
void VectorEditorController::deleteSelectedGraphicsPrimitive ()
Deletes the selected graphics primitive from the vector editor model.
This function creates a DeletePrimitiveAction with the model as a parameter and executes it to delete the selected graphics primitive from the active document in the model. The DeletePrimitiveAction also stores the deleted primitive and its index. After executing the action, it is added to the action history stack.
See also
DeletePrimitiveAction
Definition at line 63 of file VectorEditorController.cpp.
{
     std::cout << "command Delete selected primitive" << std::endl;
     auto action = std::make_shared<DeletePrimitiveAction>(_model);
     action->Execute();
     _actionHistory.push(action);
 }
openDocument()
void VectorEditorController::openDocument (std::string_view filePath)
Opens a document in the vector editor.
This function opens a document in the vector editor based on the specified file path.
If the active document is not empty, the function creates an action composition with two actions:
CloseDocumentAction to close the current active document
OpenDocumentAction to open the new document specified by the file path
If the active document is empty, the function creates an OpenDocumentAction to open the new document.
The function then executes the created action and adds it to the action history stack.
Parameters
filePath The file path of the document to be opened.
See also
CloseDocumentAction
OpenDocumentAction
Definition at line 9 of file VectorEditorController.cpp.
{
     std::cout << "command Open document" << std::endl;
     std::shared_ptr<IUserAction> action;
     if (_model->getActiveDocument() != nullptr)
     {
         auto command = std::make_shared<ActionComposition>();
         command->addAction(CloseDocumentAction(_model));
         command->addAction(OpenDocumentAction(_model, filePath));
         action = command;
     }
     else
     {
         action = std::make_shared<OpenDocumentAction>(_model, filePath);
     }
     action->Execute();
     _actionHistory.push( action );
 }
Referenced by main().
redo()
void VectorEditorController::redo ()
Redo the last undone action.
This function redoes the last undone action by popping it from the canceled actions stack, executing it, and pushing it back to the action history stack.
If the canceled actions stack is empty, this function does nothing.
See also
IUserAction::Execute()
Definition at line 88 of file VectorEditorController.cpp.
{
     std::cout << "command Redo" << std::endl;
     if (_canceledActions.empty())
         return;
     auto action = _canceledActions.top();
     _canceledActions.pop();
     action->Execute();
     _actionHistory.push(action);
 }
saveDocument()
VectorEditorController::saveDocument (std::string_view filePath)
Saves the active document to a file.
This function saves the active document in the vector editor to the specified file path. It creates a SaveDocumentToFile action with the model and file path as parameters. The action is then executed to save the document, and added to the action history stack.
Parameters
filePath The file path where the document will be saved.
See also
SaveDocumentToFile
Definition at line 35 of file VectorEditorController.cpp.
{
     std::cout << "command Save document" << std::endl;
     auto action = std::make_shared<SaveDocumentToFile>(_model, filePath);
     action->Execute();
     _actionHistory.push( action );
 }
Referenced by main().
selectGraphicsPrimitives()
void VectorEditorController::selectGraphicsPrimitives (Point point)
Selects graphics primitives based on the given point.
This function creates a shared pointer to a SelectPrimitiveAction object, passing the model and the specified point as parameters. It then invokes the Execute() method of the SelectPrimitiveAction object. Finally, the action is added to the action history.
Parameters
point The point to be used for selecting graphics primitives.
Definition at line 70 of file VectorEditorController.cpp.
{
     std::cout << "command Select primitive by point" << std::endl;
     auto action = std::make_shared<SelectPrimitiveAction>(_model, point);
     action->Execute();
     _actionHistory.push(action);
 }
undo()
void VectorEditorController::undo ()
Undo the last action performed.
This function retrieves the last action from the action history and performs its undo operation. The action is then added to the canceled actions stack.
If the action history is empty, this function does nothing.
See also
Action::Undo()
Definition at line 77 of file VectorEditorController.cpp.
{
     std::cout << "command Undo" << std::endl;
     if (_actionHistory.empty())
         return;
     auto action = _actionHistory.top();
     _actionHistory.pop();
     action->Undo();
     _canceledActions.push(action);
 }
Referenced by main().
The documentation for this class was generated from the following files:
VectorEditorController.h
VectorEditorController.cpp